customhost = "employee.ci9cl96hqxwx.ap-south-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee"
custombucket = "addemployee"
customregion = "us-south-1"
